const MOVIES_DATA = [
    { 
        id: 1, 
        title: "Дюна: Часть вторая", 
        titleEn: "Dune: Part Two",
        rating: 8.3, 
        year: 2024, 
        genre: ["Фантастика", "Драма"], 
        poster: "дюна.webp",
        backdrop: "дюна.webp",
        duration: "166 мин",
        director: "Дени Вильнёв",
        description: "Пол Атрейдес объединяется с фрименами, чтобы отомстить за свою семью и спасти вселенную.",
        cast: ["Тимоти Шаламе", "Зендея", "Остин Батлер"],
        top5: true,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 2, 
        title: "Оппенгеймер", 
        titleEn: "Oppenheimer",
        rating: 8.5, 
        year: 2023, 
        genre: ["Драма", "Триллер"], 
        poster: "опен.webp",
        backdrop: "опен.webp",
        duration: "180 мин",
        director: "Кристофер Нолан",
        description: "История создания атомной бомбы и человека, который изменил ход истории.",
        cast: ["Киллиан Мёрфи", "Роберт Дауни мл.", "Эмили Блант"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 3, 
        title: "Интерстеллар", 
        titleEn: "Interstellar",
        rating: 8.6, 
        year: 2014, 
        genre: ["Фантастика", "Драма"], 
        poster: "инт.webp",
        backdrop: "инт.webp",
        duration: "169 мин",
        director: "Кристофер Нолан",
        description: "Команда исследователей отправляется через червоточину в поисках нового дома для человечества.",
        cast: ["Мэттью Макконахи", "Энн Хэтэуэй", "Джессика Честейн"],
        top5: true,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 4, 
        title: "Побег из Шоушенка", 
        titleEn: "The Shawshank Redemption",
        rating: 9.1, 
        year: 1994, 
        genre: ["Драма"], 
        poster: "поб.png",
        backdrop: "поб.png",
        duration: "142 мин",
        director: "Фрэнк Дарабонт",
        description: "Бухгалтер Энди Дюфрейн оказывается в тюрьме за преступление, которого не совершал.",
        cast: ["Тим Роббинс", "Морган Фриман"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 5, 
        title: "Начало", 
        titleEn: "Inception",
        rating: 8.7, 
        year: 2010, 
        genre: ["Фантастика", "Боевик"], 
        poster: "нач.jpg",
        backdrop: "нач.jpg",
        duration: "148 мин",
        director: "Кристофер Нолан",
        description: "Вор, крадущий секреты из снов, получает задание внедрить идею в чужое подсознание.",
        cast: ["Леонардо ДиКаприо", "Том Харди", "Эллиот Пейдж"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 6, 
        title: "Джокер", 
        titleEn: "Joker",
        rating: 8.2, 
        year: 2019, 
        genre: ["Драма", "Триллер"], 
        poster: "джок.jpg",
        duration: "122 мин",
        description: "История становления одного из самых известных злодеев Готэма.",
        cast: ["Хоакин Феникс", "Роберт Де Ниро"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 7, 
        title: "Матрица", 
        titleEn: "The Matrix",
        rating: 8.5, 
        year: 1999, 
        genre: ["Фантастика", "Боевик"], 
        poster: "матр.jpg",
        duration: "136 мин",
        description: "Хакер Нео узнаёт, что его реальность — это симуляция.",
        cast: ["Киану Ривз", "Лоуренс Фишбёрн"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 8, 
        title: "Головоломка 2", 
        titleEn: "Inside Out 2",
        rating: 7.6, 
        year: 2024, 
        genre: ["Анимация", "Комедия"], 
        poster: "гол.webp",
        duration: "96 мин",
        description: "Райли вступает в подростковый возраст, и у неё появляются новые эмоции.",
        cast: ["Эми Полер", "Майя Хоук"],
        top5: false,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 9, 
        title: "Дэдпул и Росомаха", 
        titleEn: "Deadpool & Wolverine",
        rating: 7.8, 
        year: 2024, 
        genre: ["Боевик", "Комедия"], 
        poster: "дэдп.jpg",
        duration: "128 мин",
        description: "Дэдпул объединяется с Росомахой для эпического приключения.",
        cast: ["Райан Рейнольдс", "Хью Джекман"],
        top5: false,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 10, 
        title: "Аватар 3", 
        titleEn: "Avatar: Fire and Ash",
        rating: 0, 
        year: 2025, 
        genre: ["Фантастика", "Боевик"], 
        poster: "ават.jpg",
        duration: "TBA",
        description: "Продолжение эпической саги на Пандоре.",
        cast: ["Сэм Уортингтон", "Зои Салдана"],
        top5: false,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 11, 
        title: "Бэтмен 2", 
        titleEn: "The Batman — Part II",
        rating: 0, 
        year: 2026, 
        genre: ["Боевик", "Триллер"], 
        poster: "бэтм.webp",
        duration: "TBA",
        description: "Брюс Уэйн продолжает борьбу с преступностью в Готэме.",
        cast: ["Роберт Паттинсон", "Зои Кравиц"],
        top5: false,
        inTheaters: false,
        comingSoon: true
    }
];