const MOVIES_DATA = [
    { 
        id: 1, 
        title: "Дюна: Часть вторая", 
        titleEn: "Dune: Part Two",
        rating: 8.3, 
        year: 2024, 
        genre: ["Фантастика", "Драма"], 
        poster: "дюна.webp",
        backdrop: "дюна.webp",
        duration: "166 мин",
        director: "Дени Вильнёв",
        description: "Пол Атрейдес объединяется с фрименами, чтобы отомстить за свою семью и спасти вселенную.",
        cast: ["Тимоти Шаламе", "Зендея", "Остин Батлер"],
        top5: true,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 2, 
        title: "Оппенгеймер", 
        titleEn: "Oppenheimer",
        rating: 8.5, 
        year: 2023, 
        genre: ["Драма", "Триллер"], 
        poster: "опен.webp",
        backdrop: "опен.webp",
        duration: "180 мин",
        director: "Кристофер Нолан",
        description: "История создания атомной бомбы и человека, который изменил ход истории.",
        cast: ["Киллиан Мёрфи", "Роберт Дауни мл.", "Эмили Блант"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 3, 
        title: "Интерстеллар", 
        titleEn: "Interstellar",
        rating: 8.6, 
        year: 2014, 
        genre: ["Фантастика", "Драма"], 
        poster: "инт.webp",
        backdrop: "инт.webp",
        duration: "169 мин",
        director: "Кристофер Нолан",
        description: "Команда исследователей отправляется через червоточину в поисках нового дома для человечества.",
        cast: ["Мэттью Макконахи", "Энн Хэтэуэй", "Джессика Честейн"],
        top5: true,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 4, 
        title: "Побег из Шоушенка", 
        titleEn: "The Shawshank Redemption",
        rating: 9.1, 
        year: 1994, 
        genre: ["Драма"], 
        poster: "поб.png",
        backdrop: "поб.png",
        duration: "142 мин",
        director: "Фрэнк Дарабонт",
        description: "Бухгалтер Энди Дюфрейн оказывается в тюрьме за преступление, которого не совершал.",
        cast: ["Тим Роббинс", "Морган Фриман"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 5, 
        title: "Начало", 
        titleEn: "Inception",
        rating: 8.7, 
        year: 2010, 
        genre: ["Фантастика", "Боевик"], 
        poster: "нач.jpg",
        backdrop: "нач.jpg",
        duration: "148 мин",
        director: "Кристофер Нолан",
        description: "Вор, крадущий секреты из снов, получает задание внедрить идею в чужое подсознание.",
        cast: ["Леонардо ДиКаприо", "Том Харди", "Эллиот Пейдж"],
        top5: true,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 6, 
        title: "Джокер", 
        titleEn: "Joker",
        rating: 8.2, 
        year: 2019, 
        genre: ["Драма", "Триллер"], 
        poster: "джок.jpg",
        backdrop: "джок.jpg",
        duration: "122 мин",
        director: "Тодд Филлипс",
        description: "История становления одного из самых известных злодеев Готэма.",
        cast: ["Хоакин Феникс", "Роберт Де Ниро"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 7, 
        title: "Матрица", 
        titleEn: "The Matrix",
        rating: 8.5, 
        year: 1999, 
        genre: ["Фантастика", "Боевик"], 
        poster: "матр.jpg",
        backdrop: "матр.jpg",
        duration: "136 мин",
        director: "Лана и Лилли Вачовски",
        description: "Хакер Нео узнаёт, что его реальность — это симуляция.",
        cast: ["Киану Ривз", "Лоуренс Фишбёрн"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 8, 
        title: "Паразиты", 
        titleEn: "Parasite",
        rating: 8.5, 
        year: 2019, 
        genre: ["Триллер", "Комедия", "Драма"], 
        poster: "пар.jpg",
        backdrop: "пар.jpg",
        duration: "132 мин",
        director: "Пон Джун-хо",
        description: "Семья Ки Тхэков живёт в полуподвале и еле сводит концы с концами.",
        cast: ["Сон Кан-хо", "Чхве У-шк"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 9, 
        title: "Мстители: Финал", 
        titleEn: "Avengers: Endgame",
        rating: 8.4, 
        year: 2019, 
        genre: ["Боевик", "Фантастика"], 
        poster: "мст.jpg",
        backdrop: "мст.jpg",
        duration: "181 мин",
        director: "Энтони и Джо Руссо",
        description: "Оставшиеся Мстители собираются вместе, чтобы обратить последствия щелчка Таноса.",
        cast: ["Роберт Дауни мл.", "Крис Эванс"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 10, 
        title: "Головоломка 2", 
        titleEn: "Inside Out 2",
        rating: 7.6, 
        year: 2024, 
        genre: ["Анимация", "Комедия"], 
        poster: "гол.webp",
        backdrop: "гол.webp",
        duration: "96 мин",
        director: "Келси Манн",
        description: "Райли вступает в подростковый возраст, и у неё появляются новые эмоции.",
        cast: ["Эми Полер", "Майя Хоук"],
        top5: false,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 11, 
        title: "Дэдпул и Росомаха", 
        titleEn: "Deadpool & Wolverine",
        rating: 7.8, 
        year: 2024, 
        genre: ["Боевик", "Комедия"], 
        poster: "дэдп.jpg",
        backdrop: "дэдп.jpg",
        duration: "128 мин",
        director: "Шон Леви",
        description: "Дэдпул объединяется с Росомахой для эпического приключения.",
        cast: ["Райан Рейнольдс", "Хью Джекман"],
        top5: false,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 12, 
        title: "Чужой: Ромул", 
        titleEn: "Alien: Romulus",
        rating: 7.3, 
        year: 2024, 
        genre: ["Ужасы", "Фантастика"], 
        poster: "чуж.jpg",
        backdrop: "чуж.jpg",
        duration: "119 мин",
        director: "Феде Альварес",
        description: "Группа колонизаторов сталкивается с ужасающей формой жизни на космической станции.",
        cast: ["Кейли Спейни", "Дэвид Йонссон"],
        top5: false,
        inTheaters: true,
        comingSoon: false
    },
    { 
        id: 13, 
        title: "Аватар 3", 
        titleEn: "Avatar: Fire and Ash",
        rating: 0, 
        year: 2025, 
        genre: ["Фантастика", "Боевик"], 
        poster: "ават.jpg",
        backdrop: "ават.jpg",
        duration: "TBA",
        director: "Джеймс Кэмерон",
        description: "Продолжение эпической саги на Пандоре.",
        cast: ["Сэм Уортингтон", "Зои Салдана"],
        top5: false,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 14, 
        title: "Мстители: Судный день", 
        titleEn: "Avengers: Doomsday",
        rating: 0, 
        year: 2026, 
        genre: ["Боевик", "Фантастика"], 
        poster: "мстт.webp",
        backdrop: "мстт.webp",
        duration: "TBA",
        director: "Энтони и Джо Руссо",
        description: "Новая эпоха Мстителей начинается.",
        cast: ["Роберт Дауни мл."],
        top5: false,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 15, 
        title: "Бэтмен 2", 
        titleEn: "The Batman — Part II",
        rating: 0, 
        year: 2026, 
        genre: ["Боевик", "Триллер", "Драма"], 
        poster: "бэтм.webp",
        backdrop: "бэтм.webp",
        duration: "TBA",
        director: "Мэтт Ривз",
        description: "Брюс Уэйн продолжает борьбу с преступностью в Готэме.",
        cast: ["Роберт Паттинсон", "Зои Кравиц"],
        top5: false,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 16, 
        title: "Форсаж 11", 
        titleEn: "Fast X: Part 2",
        rating: 0, 
        year: 2026, 
        genre: ["Боевик"], 
        poster: "форс.webp",
        backdrop: "форс.webp",
        duration: "TBA",
        director: "Луис Летерье",
        description: "Дом Торетто и его семья возвращаются для финальной гонки.",
        cast: ["Вин Дизель"],
        top5: false,
        inTheaters: false,
        comingSoon: true
    },
    { 
        id: 17, 
        title: "Тёмный рыцарь", 
        titleEn: "The Dark Knight",
        rating: 9.0, 
        year: 2008, 
        genre: ["Боевик", "Драма", "Триллер"], 
        poster: "темн.jpg",
        backdrop: "темн.jpg",
        duration: "152 мин",
        director: "Кристофер Нолан",
        description: "Бэтмен поднимает ставки в войне с криминалом.",
        cast: ["Кристиан Бейл", "Хит Леджер"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 18, 
        title: "Бойцовский клуб", 
        titleEn: "Fight Club",
        rating: 8.7, 
        year: 1999, 
        genre: ["Драма", "Триллер"], 
        poster: "бойц.jpg",
        backdrop: "бойц.jpg",
        duration: "139 мин",
        director: "Дэвид Финчер",
        description: "Офисный работник и торговец мылом создают подпольный бойцовский клуб.",
        cast: ["Брэд Питт", "Эдвард Нортон"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 19, 
        title: "Список Шиндлера", 
        titleEn: "Schindler's List",
        rating: 8.9, 
        year: 1993, 
        genre: ["Драма"], 
        poster: "спи.webp",
        backdrop: "спи.webp",
        duration: "195 мин",
        director: "Стивен Спилберг",
        description: "История Оскара Шиндлера, спасшего более тысячи евреев во время Холокоста.",
        cast: ["Лиам Нисон", "Рэйф Файнс"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    },
    { 
        id: 20, 
        title: "Крёстный отец", 
        titleEn: "The Godfather",
        rating: 8.7, 
        year: 1972, 
        genre: ["Драма", "Триллер"], 
        poster: "крест.jpg",
        backdrop: "крест.jpg",
        duration: "175 мин",
        director: "Фрэнсис Форд Коппола",
        description: "История семьи Корлеоне — одного из самых могущественных кланов мафии.",
        cast: ["Марлон Брандо", "Аль Пачино"],
        top5: false,
        inTheaters: false,
        comingSoon: false
    }
];

const QUOTES_DATA = [
    { text: "Я собираюсь предложить ему то, от чего он не сможет отказаться.", author: "Крёстный отец" },
    { text: "Надеюсь, что Тихий океан достаточно велик.", author: "Побег из Шоушенка" },
    { text: "Зачем так серьёзно?", author: "Тёмный рыцарь" },
    { text: "Я — Грут.", author: "Стражи Галактики" },
    { text: "С большой силой приходит большая ответственность.", author: "Человек-паук" },
    { text: "Вот это поворот!", author: "Бойцовский клуб" },
    { text: "Я твой отец.", author: "Звёздные войны" },
    { text: "Жизнь — как коробка шоколадных конфет.", author: "Форрест Гамп" },
    { text: "Пусть будет так. Я — неизбежность.", author: "Мстители: Война бесконечности" }
];

const GENRES = ["Боевик", "Драма", "Комедия", "Фантастика", "Триллер", "Ужасы", "Анимация"];